//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
     public partial class ButtonSpaces
    {
        public long Id { get; set; }
        public long Reminders { get; set; }
        public long Timer { get; set; }
        public long BackupImport { get; set; }
        public long Settings { get; set; }
        public long SoundEffects { get; set; }
        public long ResizePopup { get; set; }
        public long MessageCenter { get; set; }
        public long DebugMode { get; set; }
    }
}
