//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
     public partial class HttpRequests
    {
        public long Id { get; set; }
        public long reminderId { get; set; }
        public string URL { get; set; }
        public string Type { get; set; }
        public string AcceptHeader { get; set; }
        public string ContentTypeHeader { get; set; }
        public string OtherHeaders { get; set; }
        public string Body { get; set; }
        public long Interval { get; set; }
        public string AfterPopup { get; set; }
    }
}
