//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
     public partial class HttpRequestCondition
    {
        public long Id { get; set; }
        public long RequestId { get; set; }
        public string Condition { get; set; }
        public string DataType { get; set; }
        public string Property { get; set; }
        public string Operator { get; set; }
        public string Value { get; set; }
    }
}
