//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
     public partial class ListviewColumnSizes
    {
        public long Id { get; set; }
        public long Title { get; set; }
        public long Date { get; set; }
        public long Repeating { get; set; }
        public long Enabled { get; set; }
    }
}
