//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalErrorLog
    {
        public int Id { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string LogContents { get; set; }
        public int LogLineCount { get; set; }
        public string Username { get; set; }
        public string UserId { get; set; }
    }
}
