//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewInstallations
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string UniqueString { get; set; }
        public System.DateTime InstallDate { get; set; }
        public string InstallVersion { get; set; }
    }
}
