//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
     public partial class PopupDimensions
    {
        public long Id { get; set; }
        public long FormWidth { get; set; }
        public long FormHeight { get; set; }
        public long FontTitleSize { get; set; }
        public long FontNoteSize { get; set; }
    }
}
