//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
     public partial class Settings
    {
        public long Id { get; set; }
        public long StickyForm { get; set; }
        public long EnableReminderCountPopup { get; set; }
        public long EnableHourBeforeReminder { get; set; }
        public Nullable<long> HideReminderConfirmation { get; set; }
        public long EnableQuickTimer { get; set; }
        public string LastVersion { get; set; }
        public string DefaultTimerSound { get; set; }
        public Nullable<long> EnableAdvancedReminders { get; set; }
        public string UniqueString { get; set; }
        public string RemindMeTheme { get; set; }
        public Nullable<long> DrawerUseColors { get; set; }
        public Nullable<long> DrawerHighlight { get; set; }
        public Nullable<long> DrawerBackground { get; set; }
        public Nullable<long> CurrentTheme { get; set; }
        public Nullable<long> MaterialDesign { get; set; }
        public long AutoUpdate { get; set; }
        public long TimerVolume { get; set; }
        public string PopupType { get; set; }
    }
}
