//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
     public partial class Themes
    {
        public long Id { get; set; }
        public long Primary { get; set; }
        public long DarkPrimary { get; set; }
        public long LightPrimary { get; set; }
        public long Accent { get; set; }
        public long TextShade { get; set; }
        public Nullable<long> Mode { get; set; }
        public string ThemeName { get; set; }
        public long IsDefault { get; set; }
    }
}
