//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAttempts
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string E_mail { get; set; }
        public string Message { get; set; }
        public string UserId { get; set; }
        public string Username { get; set; }
    }
}
