//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Misc
    {
        public string DbViewerPw { get; set; }
        public int TimersCreated { get; set; }
        public int RemindersCreated { get; set; }
        public int ExportCount { get; set; }
        public int ImportCount { get; set; }
        public int MessageCount { get; set; }
        public int Id { get; set; }
        public int RecoverCount { get; set; }
        public int PreviewCount { get; set; }
        public int DuplicateCount { get; set; }
        public int HideCount { get; set; }
        public int PostponeCount { get; set; }
        public int SkipCount { get; set; }
        public int PermanentelyDeleteCount { get; set; }
    }
}
