//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access_Layer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class remindmesqldbEntities : DbContext
    {
        public remindmesqldbEntities()
            : base("name=remindmesqldbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ExceptionLog> ExceptionLog { get; set; }
        public virtual DbSet<UpdateLog> UpdateLog { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<EmailAttempts> EmailAttempts { get; set; }
        public virtual DbSet<NewInstallations> NewInstallations { get; set; }
        public virtual DbSet<LocalErrorLog> LocalErrorLog { get; set; }
        public virtual DbSet<Misc> Misc { get; set; }
        public virtual DbSet<RemindMeMessages> RemindMeMessages { get; set; }
    }
}
