//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemindMeMessages
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public string NotificationType { get; set; }
        public Nullable<int> NotificationDuration { get; set; }
        public Nullable<int> NotificationOnTop { get; set; }
        public Nullable<System.DateTime> DateOfCreation { get; set; }
        public string MeantForSpecificVersion { get; set; }
        public int ReadByAmountOfUsers { get; set; }
        public string MeantForSpecificUser { get; set; }
        public string MeantForSpecificPerson { get; set; }
    }
}
