//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateLog
    {
        public System.DateTime UpdateDate { get; set; }
        public string UpdateVersion { get; set; }
        public string Username { get; set; }
        public int Id { get; set; }
        public string PreviousVersion { get; set; }
    }
}
