//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemindMe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RemindMeDbEntities : DbContext
    {
        public RemindMeDbEntities()
            : base("name=RemindMeDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Reminder> Reminder { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<Songs> Songs { get; set; }
    }
}
